# Array Operations: 
Create two numpy arrays of size 5x5 and perform element-wise addition, subtraction, multiplication, and division.

Create Arrays: First, you need to create two numpy arrays, each of size 5x5. You can generate these arrays randomly or initialize them with specific values.

Element-wise Operations: Once you have your arrays, you'll perform four basic arithmetic operations on them element-wise: addition, subtraction, multiplication, and division.

Addition: Add corresponding elements of the two arrays together.
Subtraction: Subtract corresponding elements of one array from the other.
Multiplication: Multiply corresponding elements of the two arrays.
Division: Divide corresponding elements of one array by the elements of the other array.

In [20]:
#import requred pakages
import numpy as np

#create lists that can be used to create array. 
#here we are using random pakage of numpy to create list of randomly generated integers

list1=np.random.randint(1,10,5)
list2=np.random.randint(1,10,5)
list3=np.random.randint(1,10,5)
list4=np.random.randint(1,10,5)
list5=np.random.randint(1,10,5)
list6=np.random.randint(1,10,5)
list7=np.random.randint(1,10,5)
list8=np.random.randint(1,10,5)
list9=np.random.randint(1,10,5)
list10=np.random.randint(1,10,5)

#requremnt is to create 5x5 array, its is multidimmessional array say 2d array.
array1=np.array([list1,list2,list3,list4,list5])
array2=np.array([list6,list7,list8,list9,list10])


#perform areth,matic operations
# 1. addition - for htis we can use 2 methods

addition = array1+array2
print(array1)
print(' '*5,'+',' '*5)
print(array2)
print(' '*5,'=',' '*5)
print(addition)

[[9 7 9 1 8]
 [8 4 2 5 6]
 [2 6 3 8 2]
 [7 2 3 5 9]
 [9 3 8 5 8]]
      +      
[[1 8 2 6 6]
 [7 6 9 3 3]
 [9 3 7 7 6]
 [7 9 9 1 8]
 [5 2 5 4 2]]
      =      
[[10 15 11  7 14]
 [15 10 11  8  9]
 [11  9 10 15  8]
 [14 11 12  6 17]
 [14  5 13  9 10]]


In [28]:
#above code is very basic level code, we can optimize the code following way.
#import requred pakages
import numpy as np

#here we are directly creating array from array fucntions, 
array1=np.random.randint(1,20,size=(5,5))
array2=np.random.randint(1,20,size=(5,5))

#using np.add() funtion to perfrom addition
addition=np.add(array1,array2)

#display output, more crative way
print(array1)
print(' '*5,'+',' '*5)
print(array2)
print(' '*5,'=',' '*5)
print(addition)


[[ 8  3 15  3 15]
 [12 12  2 12 16]
 [ 1  5 19 19  4]
 [15 18  6  2 16]
 [10 15  1 14 16]]
      +      
[[19  7  1  4 19]
 [ 4  9  6 16  9]
 [13 13 19 13  5]
 [17  6 15  7  1]
 [15 12 16 16 12]]
      =      
[[27 10 16  7 34]
 [16 21  8 28 25]
 [14 18 38 32  9]
 [32 24 21  9 17]
 [25 27 17 30 28]]


In [32]:
#similler way we can perform subtraction, first create 2 arrays

array3=np.random.randint(11,30,size=(5,5))
array4=np.random.randint(11,30,size=(5,5))

#perform subtrcation
subtraction=np.subtract(array3,array4)

#display output
print(array3)
print(' '*5,'-',' '*5)
print(array4)
print(' '*5,'=',' '*5)
print(subtraction)



[[11 20 22 27 23]
 [14 21 21 13 11]
 [27 18 18 21 27]
 [28 21 15 16 21]
 [12 12 24 13 28]]
      -      
[[26 29 18 15 18]
 [22 11 18 19 18]
 [27 23 25 28 22]
 [25 19 29 26 23]
 [12 22 14 16 24]]
      =      
[[-15  -9   4  12   5]
 [ -8  10   3  -6  -7]
 [  0  -5  -7  -7   5]
 [  3   2 -14 -10  -2]
 [  0 -10  10  -3   4]]


In [35]:
#now lets perform multiplacation
array5=np.random.randint(11,30,size=(5,5))
array6=np.random.randint(11,30,size=(5,5))
multi=np.multiply(array5,array6)
print(array5)
print(' '*5,'*',' '*5)
print(array6)
print(' '*5,'=',' '*5)
print(multi)

[[25 19 19 14 12]
 [18 13 29 15 22]
 [17 21 28 26 11]
 [11 13 28 13 12]
 [20 15 16 29 11]]
      *      
[[27 13 15 12 22]
 [21 27 14 13 29]
 [19 17 28 17 13]
 [13 12 28 16 25]
 [12 24 15 25 13]]
      =      
[[675 247 285 168 264]
 [378 351 406 195 638]
 [323 357 784 442 143]
 [143 156 784 208 300]
 [240 360 240 725 143]]


In [38]:
#perform devision 
array7=np.random.randint(11,30,size=(5,5))
array8=np.random.randint(11,30,size=(5,5))
divide=np.divide(array7,array8)
print(array7)
print(' '*5,'/',' '*5)
print(array8)
print(' '*5,'=',' '*5)
print(divide)

[[28 14 26 16 17]
 [14 24 25 21 12]
 [16 26 18 15 15]
 [12 18 17 29 26]
 [11 11 22 12 26]]
      /      
[[27 13 26 21 17]
 [24 21 27 13 11]
 [25 17 12 27 21]
 [25 19 15 28 25]
 [17 28 17 24 20]]
      =      
[[1.03703704 1.07692308 1.         0.76190476 1.        ]
 [0.58333333 1.14285714 0.92592593 1.61538462 1.09090909]
 [0.64       1.52941176 1.5        0.55555556 0.71428571]
 [0.48       0.94736842 1.13333333 1.03571429 1.04      ]
 [0.64705882 0.39285714 1.29411765 0.5        1.3       ]]


# Statistics Calculation: 
Generate a numpy array of 100 random numbers and calculate the mean, median, standard deviation, and variance.

# functions used

1.mean() - mean value is avag value of series, it is the sum of all elemnts of series devided the total no of the series.

2.median() - median is middle value of series, this value devide the whole series into two eqaul parts, one part has all lower values while other parts has all higher values.

3.std() - standerd deviation is measure that, how data is distributed about mean value. wheather data is clustered near to mean value or it spread arround. 

4.var() - varience defines how much data is deviated form its mean value.

In [46]:
#calculate array of 100 elments
array1=np.random.randint(1,101,size=100)
#calculate mean
mean_value = np.mean(array1)
print(array1)
print('-'*80)
print('mean of above array is: ',mean_value)


[ 4  1 40 36  6 36 71 86 12 60 95 39 66  7 43 28 40 56 12 18 97  7 66 60
 83 77 54 65 10 27 23 92 16 14 55 46 64 20 67 44 89 87 42 72 15 55 15 72
 35  6 13 19 35 10 24 84 12 88 14 27 41 54  2  2 46 37 33 84 62 81 18 90
 89 25 65 48 94 10 56 85 55 62 34 65 21 24 46 45 12 76 50 13 33  8 95 53
 70 11 56 30]
--------------------------------------------------------------------------------
mean of above array is:  44.38


In [52]:
#calculate array of 10 elments
array1=np.random.randint(1,11,size=10)
#calculate median
med_value = np.median(array1)
#display results
print(array1)
print('-'*30)
print('median of above array is: ',med_value)

[ 7 10  3  5  3  9 10  2  7  8]
------------------------------
median of above array is:  7.0


In [11]:
import numpy as np
array2=np.random.randint(1,30,15)
std_deviation=np.std(array2)
print(array2)
print('-'*30)
print('std dev of above array is: ', round(std_deviation,4))

[18 12 23 10 15 22 14  3 21 14 22 16  6  5 21]
------------------------------
std dev of above array is:  6.3477


In [14]:
import numpy as np
array3=np.random.randint(1,20,5)
var=np.var(array3)
print(array3)
print('-'*30)
print('varience of above array is: ', var)


[ 6 16  7 15  6]
------------------------------
varience of above array is:  20.4


# Matrix Multiplication: 
Create two matrices of size 3x3 and perform matrix multiplication using numpy.

In [29]:
#import requred pakage
import numpy as np
#create array using rand function, of gives size
array1 = np.random.randint(1,10,size=(3,3)) 
array2 = np.random.randint(1,10,size=(3,3)) 
#perform matrix multiplacation using 2 diff methods
array1.dot(array2)
print(array1.dot(array2))
print(np.matmul(array1,array2))


[[119  56  74]
 [110  94  89]
 [ 99  55  73]]
[[119  56  74]
 [110  94  89]
 [ 99  55  73]]


# Indexing and Slicing: 
Create a numpy array of shape (5, 5) and print its 2nd row,
3rd column, and 

elements from the 2nd row to the 4th row and 1st column to the 3rd column.

In [1]:
#import requred pakage
import numpy as np
#create array
array5=np.random.randint(1,50,size=(5,5))
#diplsay array
print(array5)
#display arra as per give slicing and indexing condition
print('2nd row',array5[1])
print('3rd column',array5[:,2])
print('2nd row to the 4th row',array5[1:5])
print('1st column to the 3rd column',array5[:,0:4])



[[13 29 38 43 16]
 [25 47 23 33  2]
 [12 17 24 14 41]
 [23 18 18 45 44]
 [23 37 28 21 31]]
2nd row [25 47 23 33  2]
3rd column [38 23 24 18 28]
2nd row to the 4th row [[25 47 23 33  2]
 [12 17 24 14 41]
 [23 18 18 45 44]
 [23 37 28 21 31]]
1st column to the 3rd column [[13 29 38 43]
 [25 47 23 33]
 [12 17 24 14]
 [23 18 18 45]
 [23 37 28 21]]


# Reshaping: 
Create a numpy array of size 20 and reshape it into a 4x5 matrix.

In [22]:
#imort requred pakage
import numpy as np
#create array 
array6=np.random.randint(1,50,20)
#reshaping 1d array
array7=array6.reshape(4,5)
print('reshaped array is:'
      ,'\n',array7)
#check array properties
print('given array size:',np.size(array7))
print('given array shape:',np.shape(array7))
print('given array is',array7.ndim,'D array')

reshaped array is: 
 [[12 39 39 44 18]
 [24 21 12 16 30]
 [ 3 12 21  5  6]
 [21 21 35 35  3]]
given array size: 20
given array shape: (4, 5)
given array is 2 D array


# Element-wise Functions: 
Create a numpy array and apply trigonometric functions (sin, cos, tan) element-wise to it.

In [32]:
#import requred pkaage
import numpy as np
#create a list that has specifc valuse
list1=[i for i in range(0,100,30)]
for i in range(0,100,30):
    list1.append(i)
#create array
array8=np.array(list1)
print('this is array:', array8)
#apply function
sin=np.sin(array8)
cos=np.cos(array8)
tan=np.tan(array8)
print('sin values:',sin)
print('cos values:',cos)
print('tan values:',tan)


this is array: [ 0 30 60 90]
sin values: [ 0.         -0.98803162 -0.30481062  0.89399666]
cos values: [ 1.          0.15425145 -0.95241298 -0.44807362]
tan values: [ 0.         -6.4053312   0.32004039 -1.99520041]


In [37]:
#optimized code v1.0
import numpy as np
array9=np.array([i for i in range(0,100,30)])
print('sin vlaues',np.sin(array9))
print('cos values',np.cos(array9))
print('tan values',np.tan(array9))


sin function vlaues [ 0.         -0.98803162 -0.30481062  0.89399666]
cos function values [ 1.          0.15425145 -0.95241298 -0.44807362]
tan function values [ 0.         -6.4053312   0.32004039 -1.99520041]


In [40]:
#optimized code v2.0
import numpy as np
print('sin vlaues',np.sin(np.array([i for i in range(0,100,30)])))
print('cos values',np.cos(np.array([i for i in range(0,100,30)])))
print('tan values',np.tan(np.array([i for i in range(0,100,30)])))

sin vlaues [ 0.         -0.98803162 -0.30481062  0.89399666]
cos values [ 1.          0.15425145 -0.95241298 -0.44807362]
tan values [ 0.         -6.4053312   0.32004039 -1.99520041]


# Sorting: 
Generate a random numpy array of size 10 and sort it in ascending and descending order.

In [44]:
import numpy as np
array=np.random.randint(1,20,10)
print('assending order:',np.sort(array))
print('desceding order:',np.sort(array)[::-1])

assending order: [ 1  3  4  5  5  6 10 10 12 13]
desceding order: [13 12 10 10  6  5  5  4  3  1]


# Masking/Replacing: 
Create a numpy array of size 10 with random integers and replace all values greater than 5 with 0.

In [51]:
import numpy as np
array=np.random.randint(1,10,10)
array[array > 5]=0
print('replaced array', array)

replaced array [0 0 0 3 4 2 0 0 1 2]


# Linear Algebra: 
Solve a system of linear equations using numpy's linear algebra capabilities.

Ax=b

Where:
A is a coefficient matrix,
x is a column vector of variables (unknowns),
b is a column vector of constants.

In [55]:
import numpy as np

# Define the coefficient matrix A
A = np.array([[2, 1], [1, -1]])

# Define the constant vector b
b = np.array([4, 1])
print(b)

# Solve the system of linear equations
x = np.linalg.solve(A, b)

print("Solution vector x:", x)


[4 1]
Solution vector x: [1.66666667 0.66666667]
